import type { Locale } from "../i18n";

const en = {
  financeNav: "Finance",
  financePayments: "Payments",
  financeRevenue: "Revenue",
  financeDebtors: "Debtors",
  financeExpenses: "Expenses",
  financePayroll: "Payroll",
  paymentsTitle: "Payment journal",
  search: "Search client...",
  revenueTitle: "Revenue report",
  revenueTotal: "Total",
  debtorsTitle: "Debtors",
  debtorsToPay: "To collect",
  debtorsEmpty: "No debtors",
  client: "Client",
  details: "Details",
  amount: "Amount",
  actions: "Actions",
  expensesTitle: "Expenses",
  payrollTitle: "Payroll",
  accrued: "Accrued",
  paid: "Paid",
  balance: "Balance",
  clientsAdd: "Add client",
  firstName: "First name",
  lastName: "Last name",
  phone: "Phone",
  email: "Email",
  telegram: "Telegram",
  addSubmit: "Add to database",
  listActive: "Active clients",
  listArchive: "Archive",
  tableName: "Client name",
  tableContact: "Contact",
  cardTitle: "Client card",
  notes: "Notes",
  pricesTitle: "Pricing and tariffs",
  pricesSubtitle: "Group passes, private lessons, and drop-in prices",
  sectionGroup: "Group subscriptions",
  sectionPrivate: "Private lessons",
  sectionPackage: "Private packages",
  sectionSingle: "Drop-in visits",
  settingsNav: "CRM Settings",
  settingsGeneral: "General",
  settingsOrganization: "Organization",
  settingsSubscriptions: "Subscriptions",
  settingsDisciplines: "Disciplines",
  settingsLocations: "Locations",
  settingsData: "Data export",
  settingsLicense: "License",
  generalTitle: "General settings",
  generalSubtitle: "Language, currency, and CRM display options.",
  locale: "Interface language",
  currency: "Currency",
  currencyDisplay: "Currency display",
  timezone: "Time zone",
  weekStart: "Week starts on",
  branding: "Header title",
  currencyPreview: "Example: €1,250",
  orgTitle: "Organization",
  orgSubtitle: "Studio name and modules",
  orgName: "Studio name",
  subsTitle: "Subscription settings",
  subsSubtitle: "Freeze policy for group passes",
  freezeEnabled: "Enable freeze",
  freezeEnabledDesc: "Clients can mark lessons as freeze without deducting balance",
  freezeMax: "Max freezes per subscription",
  freezeMin: "Min lessons to allow freeze",
  policySummary: "Up to {max} freezes when balance ≥ {min} lessons",
  disciplinesTitle: "Disciplines",
  locationsTitle: "Locations",
  dataTitle: "Data export",
  dataHint: "Export clients, subscriptions, and payments to CSV",
  exportBtn: "Export data",
  licenseTitle: "License",
  licenseActive: "Lifetime access · TangoDB CRM v2",
  teamTitle: "Team",
  teamSubtitle: "Invite staff and manage roles",
  teamInvite: "Invite member",
  teamMembers: "Team members",
  teamPending: "Pending invites",
  inviteEmail: "Email",
  inviteRole: "Role",
  sendInvite: "Send invite",
  personalSellTitle: "Sell private lesson",
  personalSellSubtitle: "Book a lesson and record payment",
  teacher: "Teacher",
  location: "Location",
  discipline: "Discipline",
  date: "Date",
  time: "Time",
  tariff: "Tariff",
  payment: "Payment",
  saveLesson: "Save lesson",
  pay: "Pay",
  telegramCol: "Telegram",
  paymentsCount: "payments",
  method: "Method",
  source: "Source",
} as const;

const ru: Record<keyof typeof en, string> = {
  financeNav: "Финансы",
  financePayments: "Платежи",
  financeRevenue: "Выручка",
  financeDebtors: "Дебиторы",
  financeExpenses: "Расходы",
  financePayroll: "Зарплаты",
  paymentsTitle: "Журнал платежей",
  search: "Поиск клиента...",
  revenueTitle: "Отчёт по выручке",
  revenueTotal: "Итого",
  debtorsTitle: "Должники",
  debtorsToPay: "К получению",
  debtorsEmpty: "Нет должников",
  client: "Клиент",
  details: "Детали",
  amount: "Сумма",
  actions: "Действия",
  expensesTitle: "Расходы",
  payrollTitle: "Зарплата преподавателям",
  accrued: "Начислено",
  paid: "Выплачено",
  balance: "Остаток",
  clientsAdd: "Добавить клиента",
  firstName: "Имя",
  lastName: "Фамилия",
  phone: "Телефон",
  email: "Email",
  telegram: "Telegram",
  addSubmit: "Добавить в базу",
  listActive: "Активные клиенты",
  listArchive: "Архив",
  tableName: "Клиент",
  tableContact: "Контакт",
  cardTitle: "Карточка клиента",
  notes: "Заметки",
  pricesTitle: "Прайс и тарифы",
  pricesSubtitle: "Групповые абонементы, персональные уроки и разовые посещения",
  sectionGroup: "Групповые абонементы",
  sectionPrivate: "Персональные уроки",
  sectionPackage: "Пакеты персональных",
  sectionSingle: "Разовые посещения",
  settingsNav: "Настройки CRM",
  settingsGeneral: "Общие",
  settingsOrganization: "Организация",
  settingsSubscriptions: "Абонементы",
  settingsDisciplines: "Направления",
  settingsLocations: "Локации",
  settingsData: "Экспорт данных",
  settingsLicense: "Лицензия",
  generalTitle: "Общие настройки",
  generalSubtitle: "Язык, валюта и отображение CRM.",
  locale: "Язык интерфейса",
  currency: "Валюта",
  currencyDisplay: "Отображение валюты",
  timezone: "Часовой пояс",
  weekStart: "Начало недели",
  branding: "Название в шапке",
  currencyPreview: "Пример: 1 250 €",
  orgTitle: "Организация",
  orgSubtitle: "Название студии и модули",
  orgName: "Название студии",
  subsTitle: "Настройки абонементов",
  subsSubtitle: "Политика заморозок для групповых абонементов",
  freezeEnabled: "Активировать заморозки",
  freezeEnabledDesc: "Клиент может отметить занятие как заморозку без списания с баланса",
  freezeMax: "Макс. заморозок на абонемент",
  freezeMin: "Мин. занятий для заморозки",
  policySummary: "До {max} заморозок при остатке ≥ {min} занятий",
  disciplinesTitle: "Направления",
  locationsTitle: "Локации / залы",
  dataTitle: "Экспорт данных",
  dataHint: "Выгрузка клиентов, абонементов и оплат в CSV",
  exportBtn: "Экспортировать",
  licenseTitle: "Лицензия",
  licenseActive: "Пожизненный доступ · TangoDB CRM v2",
  teamTitle: "Команда",
  teamSubtitle: "Приглашение сотрудников и роли",
  teamInvite: "Пригласить сотрудника",
  teamMembers: "Сотрудники",
  teamPending: "Ожидающие приглашения",
  inviteEmail: "Email",
  inviteRole: "Роль",
  sendInvite: "Отправить приглашение",
  personalSellTitle: "Продажа персонального урока",
  personalSellSubtitle: "Запись урока и приём оплаты",
  teacher: "Преподаватель",
  location: "Зал",
  discipline: "Направление",
  date: "Дата",
  time: "Время",
  tariff: "Тариф",
  payment: "Оплата",
  saveLesson: "Сохранить урок",
  pay: "Оплатить",
  telegramCol: "Telegram",
  paymentsCount: "оплат",
  method: "Способ",
  source: "Источник",
};

export type PanelStrings = typeof en;

export function panelStrings(locale: Locale): PanelStrings {
  return locale === "ru" ? (ru as PanelStrings) : en;
}
