import type { Locale } from "../i18n";

const en = {
  nav: {
    analytics: "Analytics",
    finance: "Finance",
    clients: "Clients",
    groupSubs: "Group subscriptions",
    scheduleJournal: "Schedule and journal",
    personal: "Private lessons",
    prices: "Pricing",
    settings: "Settings",
    dashboard: "Overview and statistics",
    financeItem: "Finance",
    clientsItem: "Client database",
    subscriptions: "Subscriptions",
    subscriptionsSell: "Sell subscription",
    schedule: "Schedule",
    attendance: "Attendance journal",
    personalLessons: "Private lessons",
    personalSell: "Sales",
    pricesItem: "Pricing and tariffs",
    settingsItem: "CRM Settings",
    team: "Team",
  },
  panel: {
    dashboard: "Overview and statistics",
    schedule: "Schedule",
    attendance: "Attendance journal",
    subscriptions: "Subscriptions",
    subscriptionsSell: "Sell subscription",
    personal: "Private lessons",
    personalSell: "Sales",
    finance: "Finance",
    clients: "Client database",
    prices: "Pricing and tariffs",
    settings: "CRM Settings",
    team: "Team",
    placeholder: "Available in the full CRM after sign-in.",
  },
  dashboard: {
    operational: "Operations",
    financial: "Finance",
    activeSubs: "Active subscriptions",
    solosPairs: "{solos} solo · {pairs} pair",
    debtorsPersonal: "Debtors (private)",
    unpaidLessons: "unpaid lessons",
    expiringSubs: "Low balance (≤{n})",
    noExpiring: "No subscriptions running low",
    balance: "Balance",
    attendance: "Attendance",
    present: "Present",
    absences: "Absent",
    freeze: "Freeze",
    openAttendance: "Open attendance journal",
    todayPayments: "Today's payments",
    financialOverview: "Financial overview",
    revenue: "Revenue",
    subscriptions: "Subscriptions",
    personal: "Private lessons",
    singleVisits: "Drop-in visits",
    receivables: "Receivables",
    expenses: "Expenses",
    payroll: "Payroll accrued",
    profit: "Profit",
    newClients: "New clients",
    occupancy: "Occupancy",
    revenueTrend: "Revenue trend",
    topClients: "Top clients",
    mom: "+{n}% vs prev. month",
    momVsPrevious: "vs prev. month",
    paymentsCount: "{n} payments",
    receivablesBreakdown: "{subs} subs · {personal} personal",
    expensesMonth: "Expenses (month)",
    payrollAccruedHint: "Accrued, not paid out",
    profitHint: "Revenue − expenses − payroll",
    revenueSplit: "Revenue split",
    revenueTrendPeriod: "6 months",
    newClientsInMonth: "in this month",
    occupancyDetail: "{present} present · {absent} absent",
    topTeachers: "Top teachers",
    noRankingData: "No data",
    financeLinksRevenue: "Revenue report",
    financeLinksDebtors: "Debtors",
    financeLinksPayments: "Payment journal",
    financeLinksRevenueDetail: "By category and period",
    financeLinksFullHistory: "Full history",
  },
  subs: {
    active: "Active",
    sell: "Sell",
    history: "History",
    sellTitle: "Sell subscription",
    sellSubtitle: "Select clients, tariff and payment method",
    client: "Client",
    discipline: "Discipline",
    tariff: "Tariff",
    activation: "Activation date",
    payment: "Payment",
    save: "Save subscription",
    demoHint: "Demo — view only",
    activeTitle: "Active subscriptions",
    activeHint: "Sorted by lowest balance first",
    searchPlaceholder: "Search client...",
    filterLocation: "Location",
    filterDiscipline: "Discipline",
    filterGroups: "Groups",
    filterAll: "All",
    filterAllDisciplines: "All disciplines",
    filterAllGroups: "All groups",
    filterExpiring: "Ending soon only",
    remainingLessons: "Lessons left",
    of: "of",
    activated: "Activated {date}",
    visits: "{visits} visits · {absences} absences",
    freezeAvailable: "Freeze available",
    suggestRenewal: "Suggest renewal",
    balanceOk: "Balance OK",
    localPriceList: "Use location price list",
    tariffLabel: "Tariff",
    groups: "Groups",
    historyTitle: "Subscription history",
    historyHint: "Filter by client, discipline or location",
    statusFinished: "Finished",
    statusActive: "Active",
  },
  personal: {
    title: "Private lessons",
    list: "Lessons",
    sell: "Sales",
    unpaid: "Unpaid",
    paid: "Paid",
    periodWeek: "Week",
    periodMonth: "Month",
    periodRange: "Period",
    filterAll: "All",
    allLocations: "All locations",
    allDisciplines: "All disciplines",
    allTeachers: "All teachers",
    searchClient: "Search client",
    searchByName: "Search by name...",
    colTime: "Time",
    colClients: "Clients",
    colFormat: "Format",
    colStatus: "Status",
    colAmount: "Amount",
    colAttendance: "Attendance",
    colActions: "Actions",
  },
  attendance: {
    legend: "Mark legend",
    present: "Present",
    absent: "Absent",
    freeze: "Freeze",
    lesson: "Lesson",
    location: "Hall A · Main studio",
  },
  demo: {
    banner: "Demo mode — view only, data is sample",
    readOnly: "View only",
  },
} as const;

const ru = {
  nav: {
    analytics: "Аналитика",
    finance: "Финансы",
    clients: "Клиенты",
    groupSubs: "Групповые абонементы",
    scheduleJournal: "Расписание и журнал",
    personal: "Персональные уроки",
    prices: "Прайс",
    settings: "Настройки",
    dashboard: "Обзор и статистика",
    financeItem: "Финансы",
    clientsItem: "База клиентов",
    subscriptions: "Абонементы",
    subscriptionsSell: "Продажа абонемента",
    schedule: "Расписание",
    attendance: "Журнал посещений",
    personalLessons: "Персональные уроки",
    personalSell: "Продажи",
    pricesItem: "Прайс и тарифы",
    settingsItem: "Настройки CRM",
    team: "Команда",
  },
  panel: {
    dashboard: "Обзор и статистика",
    schedule: "Расписание",
    attendance: "Журнал посещений",
    subscriptions: "Абонементы",
    subscriptionsSell: "Продажа абонемента",
    personal: "Персональные уроки",
    personalSell: "Продажи",
    finance: "Финансы",
    clients: "База клиентов",
    prices: "Прайс и тарифы",
    settings: "Настройки CRM",
    team: "Команда",
    placeholder: "Раздел доступен в полной CRM после входа.",
  },
  dashboard: {
    operational: "Операции",
    financial: "Финансы",
    activeSubs: "Активные абонементы",
    solosPairs: "{solos} соло · {pairs} пара",
    debtorsPersonal: "Должники (перс.)",
    unpaidLessons: "неоплаченных уроков",
    expiringSubs: "Мало занятий (≤{n})",
    noExpiring: "Нет абонементов с низким остатком",
    balance: "Остаток",
    attendance: "Посещения",
    present: "Пришли",
    absences: "Не пришли",
    freeze: "Заморозка",
    openAttendance: "Открыть журнал посещений",
    todayPayments: "Оплаты сегодня",
    financialOverview: "Финансовый обзор",
    revenue: "Выручка",
    subscriptions: "Абонементы",
    personal: "Персональные",
    singleVisits: "Разовые",
    receivables: "Дебиторка",
    expenses: "Расходы",
    payroll: "Зарплата",
    profit: "Прибыль",
    newClients: "Новые клиенты",
    occupancy: "Заполняемость",
    revenueTrend: "Динамика выручки",
    topClients: "Топ клиентов",
    mom: "+{n}% к пред. месяцу",
    momVsPrevious: "к пред. месяцу",
    paymentsCount: "{n} оплат",
    receivablesBreakdown: "{subs} абон. · {personal} перс.",
    expensesMonth: "Расходы (месяц)",
    payrollAccruedHint: "Начислено, не выплачено",
    profitHint: "Выручка − расходы − зарплата",
    revenueSplit: "Структура выручки",
    revenueTrendPeriod: "6 мес.",
    newClientsInMonth: "за месяц",
    occupancyDetail: "{present} пришли · {absent} не пришли",
    topTeachers: "Топ преподавателей",
    noRankingData: "Нет данных",
    financeLinksRevenue: "Отчёт по выручке",
    financeLinksDebtors: "Должники",
    financeLinksPayments: "Журнал оплат",
    financeLinksRevenueDetail: "По категориям и периоду",
    financeLinksFullHistory: "Полная история",
  },
  subs: {
    active: "Действующие",
    sell: "Продажа",
    history: "История",
    sellTitle: "Продажа абонемента",
    sellSubtitle: "Выберите клиентов, тариф и способ оплаты",
    client: "Клиент",
    discipline: "Направление",
    tariff: "Тариф",
    activation: "Дата активации",
    payment: "Оплата",
    save: "Сохранить абонемент",
    demoHint: "Демо — только просмотр",
    activeTitle: "Действующие абонементы",
    activeHint: "Сортировка по наименьшему остатку",
    searchPlaceholder: "Поиск клиента...",
    filterLocation: "Локация",
    filterDiscipline: "Направление",
    filterGroups: "Группы",
    filterAll: "Все",
    filterAllDisciplines: "Все направления",
    filterAllGroups: "Все группы",
    filterExpiring: "Только заканчивающиеся",
    remainingLessons: "Остаток занятий",
    of: "из",
    activated: "Активирован {date}",
    visits: "{visits} посещений · {absences} пропусков",
    freezeAvailable: "Заморозка доступна",
    suggestRenewal: "Предложить продление",
    balanceOk: "Остаток в норме",
    localPriceList: "Прайс локации",
    tariffLabel: "Тариф",
    groups: "Группы",
    historyTitle: "История абонементов",
    historyHint: "Фильтр по клиенту, направлению или локации",
    statusFinished: "Завершён",
    statusActive: "Активен",
  },
  personal: {
    title: "Персональные уроки",
    list: "Уроки",
    sell: "Продажи",
    unpaid: "Не оплачен",
    paid: "Оплачен",
    periodWeek: "Неделя",
    periodMonth: "Месяц",
    periodRange: "Период",
    filterAll: "Все",
    allLocations: "Все локации",
    allDisciplines: "Все направления",
    allTeachers: "Все преподаватели",
    searchClient: "Поиск клиента",
    searchByName: "Поиск по имени...",
    colTime: "Время",
    colClients: "Клиенты",
    colFormat: "Формат",
    colStatus: "Статус",
    colAmount: "Сумма",
    colAttendance: "Посещение",
    colActions: "Действия",
  },
  attendance: {
    legend: "Обозначения",
    present: "Пришёл",
    absent: "Не пришёл",
    freeze: "Заморозка",
    lesson: "Занятие",
    location: "Зал A · Основная студия",
  },
  demo: {
    banner: "Демо — только просмотр, данные примерные",
    readOnly: "Только просмотр",
  },
};

export function crmStrings(locale: Locale): CrmStrings {
  return locale === "ru" ? (ru as CrmStrings) : en;
}

export type CrmStrings = typeof en;
